
DROP DATABASE IF EXISTS codeCollab_db;
CREATE DATABASE codeCollab_db;
USE codeCollab_db;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(30) NOT NULL,
  userEmail VARCHAR(30) NOT NULL,
  userPassword VARCHAR(30) NOT NULL
);

CREATE TABLE language (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  JavaScript BOOLEAN NOT NULL,
  Python BOOLEAN NOT NULL,
  Java BOOLEAN NOT NULL,
  Swift BOOLEAN NOT NULL
);

CREATE TABLE post (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 content VARCHAR(100) NOT NULL,
 imageLink VARCHAR(150),
 FOREIGN KEY (userId) REFERENCES users(id)
);
