
DROP DATABASE IF EXISTS db_codeCollab;
CREATE DATABASE db_codeCollab;
USE db_codeCollab;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userName VARCHAR(30) NOT NULL,
  userEmail VARCHAR(30) NOT NULL,
  userPassword VARCHAR(30) NOT NULL,
);

CREATE TABLE languages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  JavaScript BOOLEAN NOT NULL,
  Python BOOLEAN NOT NULL,
  Java BOOLEAN NOT NULL,
  Swift BOOLEAN NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE posts (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 content VARCHAR(100) NOT NULL,
 imageLink VARCHAR(150),
 FOREIGN KEY (userId) REFERENCES users(id)
);
